# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests

name: Release

on:
  release:
    types: [published]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}
          context: .
      - name: Restart container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.SSH_COMMAND }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
